### ISSUE TITLE
INFO : NVD Feed supply

### ISSUE THREAD

**Issue by remycx** [owasp-dep-scan/dep-scan#107]
Greetings,

From what I can read, you get NVD feeds from the yearly JSON files feed. However, these feed become deprecated in roughly 2, 2.5 months (see https://nvd.nist.gov/vuln/data-feeds : In September 2023, the NVD plans to retire all legacy data feeds while guiding any remaining data feed users to updated application-programming interfaces (APIs))

Just a head's up :)

**Comment by marcelstoer** [comment]
Is this ticket still relevant? The feeds should long have been retired but NIST seems reluctant to actually pull the plug. 

P.S. OWASP Dependency Check switched to the NVD API through [their own API client](https://github.com/jeremylong/Open-Vulnerability-Project/tree/main/open-vulnerability-clients).

**Comment by marcelstoer** [comment]
I mean, shouldn't this issue rather be with https://github.com/AppThreat/vulnerability-db?

> I will revisit next week to see if the APIs are scaling.

Yeah, I remember from using OWASP Dependency Check 9+ that the NVD API had difficulties at the beginning - even when using an API key. Haven't noticed any issues for several weeks now.

**Comment by prabhu** [comment]
vuln-list is now getting the data from the API

https://github.com/AppThreat/vuln-list/tree/main/nvd

Will work on a branch in vulnerability-db to use this folder.
