### ISSUE TITLE
Version of depscan

### ISSUE THREAD

**Issue by algomaster99** [owasp-dep-scan/dep-scan#121]
Hi! It would be nice to have a `-v` or `--version` flag in the binary so that I can view the version of depscan I am using. An enhancement over this could be to store the version of the depscan in [reports](https://github.com/ASSERT-KTH/sbom.exe/blob/main/watchdog-agent/src/test/resources/pdfbox-3.0.0/sbom-universal.json) generated by it.

**Comment by prabhu** [comment]
Hi @algomaster99, it's a useful feature. Would you be interested in contributing this?

As per this [thread](https://github.com/python-poetry/poetry/issues/273), the below snippet works

```
>>> import pkg_resources
>>> my_version = pkg_resources.get_distribution('my-package-name').version
```

The metadata.tools [section](https://cyclonedx.org/docs/1.5/json/#metadata_tools) can be updated to append the details about depscan. The [version](https://cyclonedx.org/docs/1.5/json/#version) can also be incremented to indicate that depscan enhanced an existing sbom.
