### ISSUE TITLE
Option: allow generating a pretty-printed VEX JSON

### ISSUE THREAD

**Issue by marcelstoer** [owasp-dep-scan/dep-scan#126]
I currently see no option to allow generating a pretty-printed VEX JSON. Not essential but nice to have. A pretty printed VEX JSON could more easily be diffed against the standard SBOM JSON.

**Comment by cerrussell** [comment]
@marcelstoer I agree. @prabhu Is there any reason we need to provide both, or shall I just add indent=x to the json.dump to pretty print?

**Comment by prabhu** [comment]
@cerrussell, let's add pretty print!
