### ISSUE TITLE
Customizable report output

### ISSUE THREAD

**Issue by heubeck** [owasp-dep-scan/dep-scan#140]
Hey there,

that you for this tool, really like it.

I'm generating vuln reports as pull-request comments from a github app that also uses cdxgen (as @prabhu knows :innocent: ).
Atm these comments are generated using [grype](https://github.com/anchore/grype), but I consider switching to dep-scan.

For my use-case neither the console report, nor the html report work, as both become very ugly as github comments.
Perfect would be either a markdown styled reported, or just some templating similar to what grype allows: https://github.com/anchore/grype?tab=readme-ov-file#using-templates

**Comment by prabhu** [comment]
@heubeck, glad you're considering depscan. We already export VDR/VEX CycloneDX json and [HTML](https://github.com/owasp-dep-scan/dep-scan/blob/master/depscan/cli.py#L784) reports.

Templating sounds like a good idea.

@cerrussell, wdyt. Is it time for some jinja magic?

**Comment by heubeck** [comment]
Yeah, the simpler the better. just accept some template in some random templating format and provide the report object to it.
