### ISSUE TITLE
Dedupe CSAF Vulnerability IDs

### ISSUE THREAD

**Issue by cerrussell** [owasp-dep-scan/dep-scan#147]
CSAF 2.0 will fail validation if the same vulnerability ID is listed more than once per vulnerability. IDs are generated programmatically by parsing the list of references. When multiple references are listed which point to the same vulnerability, a duplicate entry is added.

Example:
`https://github.com/advisories/GHSA-v845-jxx5-vc9f`
`https://github.com/urllib3/urllib3/security/advisories/GHSA-v845-jxx5-vc9f`

Both references may be included but we must only add a single entry in the IDs section.

Similarly, since commit and issue IDs are not unique, we should extract the repository name and include it in the system name.

**Comment by prabhu** [comment]
How do other vendors handle this scenario? Any examples we can find from providers such as redhat?

**Comment by cerrussell** [comment]
I'm afraid I don't know how vendors handle this - according to the generator section, Red Hat's CSAFs are produced using the Red Hat SDEngine, but I don't know any details. 

The CSAF 2.0 schema is clear that it must be unique entries and there isn't any reason to store the exact same thing twice for the same vulnerability anyway. It doesn't have to be unique across the whole document, just in the ids attached per vulnerability. There's really only two ways to deal with this issue - either prevent duplicate IDs from being generated in the first place from the reference list, or remove them afterwards. The latter is quicker.

![image](https://github.com/owasp-dep-scan/dep-scan/assets/80227828/6daae6eb-e2fc-4958-92f9-24015ef48238)

**Comment by prabhu** [comment]
Does this tool help? Perhaps the product tree is used to link to all products that are related to the given vulnerability?

https://secvisogram.github.io/?tab=EDITOR

**Comment by cerrussell** [comment]
@prabhu This is unrelated to the product tree. The entries duplicated are in vulnerabilities, and their only fields are system_name and text - for the system that created the id, and the id itself, respectively.

**Comment by cerrussell** [comment]
@prabhu Here's an [overview](https://docs.oasis-open.org/csaf/csaf/v2.0/os/csaf-v2.0-os.html#3236-vulnerabilities-property---ids) of the part of the document I am referring to from oasis.
