### ISSUE TITLE
Document SCAN_DEBUG_MODE

### ISSUE THREAD

**Issue by marcelstoer** [owasp-dep-scan/dep-scan#155]
While debugging an issue with depscan I found by coincidence that I can set `SCAN_DEBUG_MODE=debug` to [enable debug logging](https://github.com/owasp-dep-scan/dep-scan/blob/master/depscan/lib/logger.py#L64).

I suggest this be mentioned in the README or, even better, exposed as a CLI switch.

**Comment by saketjajoo** [comment]
Closing this issue as `--debug` is added as a CLI switch in https://github.com/owasp-dep-scan/dep-scan/commit/7e78a94c650014beea38e9ffd3d94deacc1f331c

**Comment by marcelstoer** [comment]
Thanks, I'd never have found it buried in that commit 😄
