### ISSUE TITLE
depscan-bom.json not valid JSON

### ISSUE THREAD

**Issue by marcelstoer** [owasp-dep-scan/dep-scan#156]
I am not sure if the automatically generated `./reports/depscan-bom.json` is considered an internal artifact or not. However, I can imagine that this file could serve use cases beyond its current range.

For processing with JSON parsers it would be helpful if it were valid JSON: turn it into an array by adding `[]` and `,`s.

**Comment by prabhu** [comment]
@marcelstoer, it is in [jsonlines](https://jsonlines.org/) format where each line is a json. This is natively supported by platforms such as BigQuery. For json format, you can use the VDR/VEX file generated with the extension .vex.json.

**Comment by marcelstoer** [comment]
Oh, never too late to learn something new, thanks! JSON Lines, never heard of this.
