### ISSUE TITLE
Feature: Filter out linux packages that don't match the distro being scanned

### ISSUE THREAD

**Issue by cerrussell** [owasp-dep-scan/dep-scan#170]
We need to filter vulnerabilities per linux distribution - for example, scanning the dep-scan docker container image should not include results for archlinux or suse, but only for almalinux since that is what we use (and possibly red hat, since rhel binaries can be installed in almalinux... ).

The scan results for the dep-scan docker [image](quay.io/appthreat/dep-scan@sha256:416045851b691c99ec03669bd735d8f4b7aaf47b7411d3e0ba441c357a26422f) on quay.io includes 134 vulnerabilities for the amazon linux version of packages, 120 for suse, 64 for rhel, and 12 for debian. That's almost half of the 677 total vulnerabilities.

[sbom-scan-updated-docker.vex.json](https://github.com/AppThreat/vulnerability-db/files/13478957/sbom-scan-updated-docker.vex.json)
[sbom-scan-updated-docker.json](https://github.com/AppThreat/vulnerability-db/files/13478958/sbom-scan-updated-docker.json)
[depscan-scan-updated-docker.json](https://github.com/AppThreat/vulnerability-db/files/13478973/depscan-scan-updated-docker.json)

**Comment by prabhu** [comment]
We may have to make this a bit more generic to handle this case.

https://github.com/owasp-dep-scan/dep-scan/blob/master/depscan/lib/analysis.py#L341
