### ISSUE TITLE
Add concurrency settings to workflows

### ISSUE THREAD

**Issue by cerrussell** [owasp-dep-scan/dep-scan#175]
I'm sure I can't be the only one who has ever needed to make a quick change after pushing to whatever branch I'm working on. It is annoying when this results in a cascade of workflow runs that are completely unnecessary. 

**Example**
I made a few quick changes to the feature/csaf-refactor branch to resolve a comment on my associated pr . Since the branch has an open pull-request associated with it, every push spawns 5 separate workflow runs. There are two each for Python matrix CI and docker tests - one for the push to a feature branch and one for the pr. The pr also creates  a run of binary and nydus tests.

This makes it very easy to generate excessive workflow runs.

I have therefore updated the workflows with the following:

```
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
``` 

This prioritizes runs spawned by the newest commits and cancels the outdated workflow runs.

**Comment by prabhu** [comment]
@cerrussell, I always assumed that such a thing is not possible with GitHub Actions. Thank you so much for adding this.
