### ISSUE TITLE
Bug: Reports not generating accurately in Ubuntu platforms

### ISSUE THREAD

**Issue by skuriyadi** [owasp-dep-scan/dep-scan#331]
### Expected Behavior

I ran the depscan on docker image "harness/delegate" (sample) in a mac os and Iinux machine and it gave different results.

In mac os it is scanning 483 oss dependencies, finds vulnerabilities and publishes the Dependency Scan Results (Docker).
In Ubuntu  it is scanning only 2 oss dependencies and find no vulnerabilities.

### Actual Behavior

The Dependency Scan result should be same in both platforms.

**Comment by prabhu** [comment]
@skuriyadi Could you share more information such as the command that was used and the output with the debug environment variable. From the description, it appears like the SBOM from cdxgen didn't include OS packages. It is possible, sudo command might be required on ubuntu to make docker work properly, so best to run cdxgen separately first and refer to the instructions in the output.

**Comment by skuriyadi** [comment]
command used: depscan --src harness/delegate --deep --explain -t docker --debug
I tried running with sudo and it did not generate the results. I tried running cdxgen seperately and referred to the output by using flag --bom and that also did not generate results either.

**Comment by prabhu** [comment]
Can you set the environment variable `CDXGEN_DEBUG_MODE=debug`, run cdxgen directly and share the output?

**Comment by skuriyadi** [comment]
I don't have any debug output generated in the console after running the command, here is the sbom-docker.json
`{“bomFormat”:“CycloneDX”,“specVersion”:“1.5",“serialNumber”:“urn:uuid:64a1189f-5a4f-4f97-b222-944ce803643d”,“version”:1,“metadata”:{“timestamp”:“2024-07-18T15:23:31.252Z”,“tools”:{“components”:[{“group”:“@cyclonedx”,“name”:“cdxgen”,“version”:“10.1.1",“purl”:“pkg:npm/%40cyclonedx/cdxgen@10.1.1",“type”:“application”,“bom-ref”:“pkg:npm/@cyclonedx/cdxgen@10.1.1",“author”:“OWASP Foundation”,“publisher”:“OWASP Foundation”}]},“authors”:[{“name”:“OWASP Foundation”}],“lifecycles”:[{“phase”:“build”},{“phase”:“post-build”}],“component”:{“name”:“harness/delegate”,“version”:“latest”,“type”:“container”,“purl”:“pkg:oci/harness/delegate@sha256:4123e55b66b7c18e1e9564c847e480cda7d71e31b6422d43e773818f0902aabe”,“bom-ref”:“pkg:oci/harness/delegate@sha256:4123e55b66b7c18e1e9564c847e480cda7d71e31b6422d43e773818f0902aabe”,“components”:[{“group”:“”,“name”:“delegate”,“version”:“latest”,“type”:“application”,“bom-ref”:“pkg:gem/delegate@latest”,“purl”:“pkg:gem/delegate@latest”},{“group”:“”,“name”:“delegate”,“version”:“latest”,“type”:“application”,“bom-ref”:“pkg:maven/delegate@latest”,“purl”:“pkg:maven/delegate@latest”}]},“properties”:[{“name”:“oci:image:Id”,“value”:“sha256:8154caed21e12a08a03695ba6e4b346a4e57ce68a16225c526f78ab7864eec78”},{“name”:“oci:image:RepoTag”,“value”:“harness/delegate:latest”},{“name”:“oci:image:RepoDigest”,“value”:“harness/delegate@sha256:4123e55b66b7c18e1e9564c847e480cda7d71e31b6422d43e773818f0902aabe”},{“name”:“oci:image:Created”,“value”:“2024-04-08T06:50:03.718701413Z”},{“name”:“oci:image:Architecture”,“value”:“arm64”},{“name”:“oci:image:Os”,“value”:“linux”},{“name”:“oci:image:manifest:Config”,“value”:“blobs/sha256/8154caed21e12a08a03695ba6e4b346a4e57ce68a16225c526f78ab7864eec78”},{“name”:“oci:image:manifest:Layers”,“value”:“blobs/sha256/346e7b163cb7be905cf1201cbcbe474e96c1ceb2d102520cc15bf34ece763dbf\\nblobs/sha256/251cb4865f49e1ce1bac6d2a0b492d9649cce61450bd98aebe323d6105682a46\\nblobs/sha256/c0d1f9b15cf5cdb76b530a462321edb6d88769c15dce93b1790a333400a41dff\\nblobs/sha256/34ec893255e2a32cfb28ec96a41fada45c0f6549882fae37ebe1bc2a2bd04418\\nblobs/sha256/98335bca28b093669906713b0ac40a39fac7fbe3f00b48a766944096ac327328\\nblobs/sha256/3cbc868bed66289359baf8620e4971cff1487a1801fbc374b535b7b45d4bbe27\\nblobs/sha256/560d94ebb7c8aae9b8433d7929ce10e28e726e775afa60ba560674f0229d09cf\\nblobs/sha256/5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef\\nblobs/sha256/17e38e968cb8ec793e3c7daa8abd77a4b68e95e0ce0a5c199b21f2627f2cba76\\nblobs/sha256/9a9d3385b442607f8ef5ff7d5ab3145633b40ecd9ef3a6442bc159cd26394824\\nblobs/sha256/22407ee1de1a635717b4ef86f774169f6ad38bdc213837329f031fdad94a5303”}]},“components”:[{“group”:“org.yaml”,“name”:“snakeyaml”,“version”:“2.0",“purl”:“pkg:maven/org.yaml/snakeyaml@2.0?type=jar”,“type”:“library”,“bom-ref”:“pkg:maven/org.yaml/snakeyaml@2.0?type=jar”,“evidence”:{“identity”:{“field”:“purl”,“confidence”:1,“methods”:[{“technique”:“manifest-analysis”,“confidence”:1,“value”:“watcher.jar”}]}},“properties”:[{“name”:“SrcFile”,“value”:“watcher.jar”}]},{“group”:“jrt-fs”,“name”:“jrt-fs”,“version”:“11.0.19",“purl”:“pkg:maven/jrt-fs/jrt-fs@11.0.19?type=jar”,“type”:“library”,“bom-ref”:“pkg:maven/jrt-fs/jrt-fs@11.0.19?type=jar”,“evidence”:{“identity”:{“field”:“purl”,“confidence”:0.5,“methods”:[{“technique”:“filename”,“confidence”:0.5,“value”:“jrt-fs.jar”}]}},“properties”:[{“name”:“SrcFile”,“value”:“jrt-fs.jar”}]}],“services”:[],“dependencies”:[{“ref”:“pkg:oci/harness/delegate@sha256:4123e55b66b7c18e1e9564c847e480cda7d71e31b6422d43e773818f0902aabe”,“dependsOn”:[]}]}`

**Comment by prabhu** [comment]
Could you test with the latest version of cdxgen? 10.1.1 is quite old.

**Comment by skuriyadi** [comment]
That worked, thank you Prabhu!

**Comment by skuriyadi** [comment]
Using the latest version of cdxgen fixed the issue.
