### ISSUE TITLE
Bug: JSON file format is not valid

### ISSUE THREAD

**Issue by anthonyharrison** [owasp-dep-scan/dep-scan#332]
### Expected Behavior

Expect valid JSON file format to be produced.

File format is

{id:"cve-....",...}
{id:"cve-....",...}
{id:"cve-....",...}

Valid format is

[
{id:"cve-....",...},
{id:"cve-....",...},
{id:"cve-....",...}
]

Note addition of `'['` at start and end of document and `','` at end of each entry

### Actual Behavior

JSON generated report is not valid. JSON standard only allows one top level entry.

### Steps to Reproduce

depscan --bom <sbomfile> --reports-dir <xx>

JSON file is stored in reports-dir

### Additional Information

Simple python script to read JSON file fails.

`data = json.load(open(filename, "r", encoding="utf-8"))`

results in JSONDecodeError

```python
Traceback (most recent call last):
  File "...../decodedata.py", line 7, in <module>
    data = json.load(open(filename, "r", encoding="utf-8"))
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 22 column 1 (char 2942)
```

**Comment by prabhu** [comment]
This file is in jsonlines format. This is going away in v6, so please use the .VDR file.
