### ISSUE TITLE
Bug: Running Depscan returns Killed

### ISSUE THREAD

**Issue by Geertkok1** [owasp-dep-scan/dep-scan#334]
### Expected Behavior

When using depscan I expect it to scan the folders to make an SBOM and check for CVE's

### Actual Behavior

It returns the following:
The depscan banner and the text Killed below it.

I did not imput anything between running the command and Killed being returned.

### Steps to Reproduce

Use an Ubuntu 20.04.6 machine.
Install CDXGen en Depscan using the manual in this repo.

### Additional Information

Is it possible that Ubuntu 20.04.6 is not supported by Depscan anymore? I have been able to run in on both Windows 11 and Ubuntu 22.04.

Both CDXGen and Depscan installed without errors.

I also tried running depscan with the --debug flag but that also just returns the banner and then killed.

**Comment by prabhu** [comment]
It must be running out of memory. Could you allocate a minimum of 8GB RAM and 15GB hdd space?

**Comment by Geertkok1** [comment]
> It must be running out of memory. Could you allocate a minimum of 8GB RAM and 15GB hdd space?

I can confirm that the machine has more that 15GB of free space on the HDD.

Does depscan by itself need 8GB of RAM or is that for the whole machine?

**Comment by prabhu** [comment]
How much free memory is available? Best to watch the process using top command and find when it crashes?

**Comment by Geertkok1** [comment]
> How much free memory is available? Best to watch the process using top command and find when it crashes?

We have increased the RAM of the machine for 8GB to 16GB and the problem is no longer there.
When I ran the top command before I saw that the machine was running out of RAM so that was indeed the issue.

Thank your for the help with troubleshooting

**Comment by prabhu** [comment]
Thank you @Geertkok1. We are looking into the memory issue for depscan v6. It will use vdb6 powered by sqlite, so doesn't require the entire index to be loaded in memory.

**Comment by dsunil-ll** [comment]
@prabhu 
I’ve encountered a similar issue where even a very small project is consuming a high amount of memory. Just checking - has the memory issue been addressed or fixed?

Thanks!
