### ISSUE TITLE
Feature: Quarkus support

### ISSUE THREAD

**Issue by tienmtran** [owasp-dep-scan/dep-scan#382]
### Request Description

I used depscan from v4 with many traditional java maven/gradle projects.

When I use depscan with a java maven quarkus project, they cannot build and generate the full sbom file. This makes the sbom file contain only some packages and the cdxgen does the same.
I read the article: https://quarkus.io/guides/cyclonedx
And I realize that maybe the maven deptree creation from cdxgen cannot be built completely for further analysis. Although I can have the maven deptree with command: mvnw dependency:tree -DoutputFile=maven_dep_tree.txt easily. Can we use an existed Maven deptree file instead of building application?

Thanks

**Comment by prabhu** [comment]
Thanks @tienmtran for this ticket. We are working on adding quarkus support in cdxgen. Will update as soon as it is ready. In the meanwhile, can you try using depscan v5 or the master with the `--bom` argument pointing to an existing SBOM?

**Comment by prabhu** [comment]
quarkus support is now available in cdxgen 11.0.5. Please wait for depscan v6 release for best results.

**Comment by tientmse62290** [comment]
Appreciate your work @prabhu <3
