### ISSUE TITLE
Support for suppression

### ISSUE THREAD

**Issue by prabhu** [owasp-dep-scan/dep-scan#4]
The tool should allow suppression of false positives. We need:

- A way of defining the suppressions. The [xml format](https://jeremylong.github.io/DependencyCheck/general/suppression.html) used by dependency-check is not suitable for the modern era. We need to think of a better yaml or toml format.
- A way of representing suppressions in the report. grafeas currently doesn't support this metadata

**Comment by marcelstoer** [comment]
> The [xml format](https://jeremylong.github.io/DependencyCheck/general/suppression.html) used by dependency-check is not suitable for the modern era.

Why so? Because it is XML?

**Comment by marcelstoer** [comment]
Should this be closed in favor of #110?

**Comment by prabhu** [comment]
Good idea!
