### ISSUE TITLE
Support for Clojure 

### ISSUE THREAD

**Issue by kakumanivrn** [owasp-dep-scan/dep-scan#57]
I really loved this snyk alternative and has great potential. Just wondering if there is any clojure support we can expect anytime soon.

**Comment by prabhu** [comment]
Thank you, @kakumanivrn, for your kind words. Could you steer me towards a sample Clojure project with open-source vulnerabilities that can be used for testing?

**Comment by kakumanivrn** [comment]
@prabhu I couldn't find one as of now. Will share it once it's available.

**Comment by prabhu** [comment]
@kakumanivrn I've added support for clojure in cdxgen.

https://github.com/AppThreat/cdxgen

Could you kindly test and let me if SBoM is getting created correctly for your projects. I will add clojure to dep-scan shortly.

**Comment by kakumanivrn** [comment]
@prabhu Yes it's working! I created bom for https://github.com/LightTable/LightTable and it's working as expected. But I am just curious if it's also parsing for indirect dependencies. 

I observed this specific code here: https://github.com/AppThreat/cdxgen/blob/9c65eba7b791f5ce686951eff0ec694795e39493/index.js#L1790

It looks like you are reading the file directly which might not have transitive dependencies. You can get complete list of dependencies using this command: https://stackoverflow.com/a/44962845

**Comment by prabhu** [comment]
Thank you. Will make this enhancement!

**Comment by kakumanivrn** [comment]
@prabhu It's working great! 

Now that cdxgen require some implicit tools to be installed, maybe we can create a simple script to install all these requirements to use cdxgen, dep-scan and vdb. I will try to collect as many commands as possible while I am trying.

**Comment by prabhu** [comment]
@kakumanivrn I am working on an sbom server, which would have a container with those tools.
