### ISSUE TITLE
Consider support for CSAF

### ISSUE THREAD

**Issue by tschmidtb51** [owasp-dep-scan/dep-scan#98]
The [Common Security Advisory Framework (CSAF)](https://docs.oasis-open.org/csaf/csaf/v2.0/csaf-v2.0.html) is the definitive reference for the language which supports creation, update, and interoperable exchange of security advisories as structured information on products, vulnerabilities and the status of impact and remediation among interested parties.

I suggest to support that framework as an additional source.

Flagging @santosomar, @sthagen for attention

**Comment by santosomar** [comment]
I echo @tschmidtb51  comments. Perhaps in the future, the scanner can also get real-time information from vendors and software suppliers CSAF feeds/repositories. This will provide the most up-to-date information about the status of the vulnerability.

**Comment by prabhu** [comment]
@tschmidtb51 @santosomar Would it be possible to meet online and discuss about this use case? My email is prabhu at appthreat dot com
